apiVersion: v1
kind: Service
metadata:
  name: risk-api-service
spec:
  type: LoadBalancer # Exposes IP (Localhost on Docker Desktop)
  selector:
    app: risk-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
